import { FoodCategory, StorageType, Priority, Donor, DemandNode } from './engine';

export const SIM_DONORS: Donor[] = [
  { id: 'd1', name: 'Central Kitchen #402', location: { lat: 37.7749, lng: -122.4194, address: 'District 7' } },
  { id: 'd2', name: 'Artisan Bakery Co.', location: { lat: 37.7849, lng: -122.4094, address: 'Downtown' } },
  { id: 'd3', name: 'WholeFoods Market', location: { lat: 37.7949, lng: -122.3994, address: 'Waterfront' } },
  { id: 'd4', name: 'Skyline Catering', location: { lat: 37.7649, lng: -122.4294, address: 'Mission' } },
  { id: 'd5', name: 'Organic Bistro', location: { lat: 37.7549, lng: -122.4394, address: 'Noe Valley' } },
  { id: 'd6', name: 'Metro Convention Ctr', location: { lat: 37.7840, lng: -122.4000, address: 'SoMa' } },
  { id: 'd7', name: 'Green Leaf Cafe', location: { lat: 37.7449, lng: -122.4294, address: 'Bernal Heights' } },
  { id: 'd8', name: 'Sunset Bakery', location: { lat: 37.7549, lng: -122.4794, address: 'Sunset' } },
  { id: 'd9', name: 'Richmond Deli', location: { lat: 37.7849, lng: -122.4694, address: 'Richmond' } },
  { id: 'd10', name: 'Union Sq Hotel', location: { lat: 37.7879, lng: -122.4074, address: 'Union Square' } },
];

export const SIM_NODES: DemandNode[] = [
  {
    id: 'n1',
    name: 'Harbor Food Bank',
    type: 'NGO',
    location: { lat: 37.7940, lng: -122.4000, address: 'Port District' },
    capacityServings: 500,
    remainingCapacity: 160,
    priority: Priority.MEDIUM,
  },
  {
    id: 'n2',
    name: 'St. Mary Shelter',
    type: 'NGO',
    location: { lat: 37.7700, lng: -122.4300, address: 'Lower Haight' },
    capacityServings: 300,
    remainingCapacity: 50,
    priority: Priority.HIGH,
  },
  {
    id: 'n3',
    name: 'Sector 5 Hunger Spot',
    type: 'HUNGER_SPOT',
    location: { lat: 37.7600, lng: -122.4100, address: 'Mission Park' },
    capacityServings: 100,
    remainingCapacity: 80,
    priority: Priority.CRITICAL,
  },
  {
    id: 'n4',
    name: 'Hope Foundation',
    type: 'NGO',
    location: { lat: 37.7800, lng: -122.4400, address: 'Richmond' },
    capacityServings: 1000,
    remainingCapacity: 800,
    priority: Priority.LOW,
  },
  {
    id: 'n5',
    name: 'Downtown Bridge Spot',
    type: 'HUNGER_SPOT',
    location: { lat: 37.7850, lng: -122.3950, address: 'Bay Bridge' },
    capacityServings: 50,
    remainingCapacity: 45,
    priority: Priority.HIGH,
  },
  {
    id: 'n6',
    name: 'Civic Center Hub',
    type: 'NGO',
    location: { lat: 37.7780, lng: -122.4180, address: 'Civic Center' },
    capacityServings: 450,
    remainingCapacity: 120,
    priority: Priority.MEDIUM,
  },
  {
    id: 'n7',
    name: 'South Beach NGO',
    type: 'NGO',
    location: { lat: 37.7810, lng: -122.3920, address: 'South Beach' },
    capacityServings: 200,
    remainingCapacity: 75,
    priority: Priority.LOW,
  },
  {
    id: 'n8',
    name: 'Marina Resource Ctr',
    type: 'NGO',
    location: { lat: 37.8030, lng: -122.4360, address: 'Marina' },
    capacityServings: 300,
    remainingCapacity: 250,
    priority: Priority.MEDIUM,
  },
  {
    id: 'n9',
    name: 'Tenderloin Spot',
    type: 'HUNGER_SPOT',
    location: { lat: 37.7830, lng: -122.4130, address: 'TL Sector 2' },
    capacityServings: 150,
    remainingCapacity: 140,
    priority: Priority.CRITICAL,
  },
  {
    id: 'n10',
    name: 'Golden Gate Park Spot',
    type: 'HUNGER_SPOT',
    location: { lat: 37.7690, lng: -122.4830, address: 'GG Park East' },
    capacityServings: 100,
    remainingCapacity: 95,
    priority: Priority.HIGH,
  },
  {
    id: 'n11',
    name: 'Potrero Hill Spot',
    type: 'HUNGER_SPOT',
    location: { lat: 37.7550, lng: -122.4010, address: 'Potrero Sector' },
    capacityServings: 80,
    remainingCapacity: 75,
    priority: Priority.MEDIUM,
  },
] as any;

export const CATEGORY_ICONS: Record<FoodCategory, string> = {
  [FoodCategory.COOKED_MEALS]: 'Utensils',
  [FoodCategory.BAKERY]: 'Croissant',
  [FoodCategory.PRODUCE]: 'Carrot',
  [FoodCategory.DAIRY]: 'Milk',
  [FoodCategory.PACKAGED]: 'Box',
};
